apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: task3
spec:
  replicas: 1
  serviceName: "minecraft"
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
        task: "3"
        challenge: three
        table: "19"
    spec:
      containers:
      - name: minecraft
        image: openhack/minecraft-server:2.0
        ports:
        - containerPort: 25565
        - containerPort: 25575
        env:
        - name: EULA
          value: "TRUE" 
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
