apiVersion: v1
kind: Service
metadata:
  labels:
    task: "3"
    app: minecraft
  name: minecraft
spec:
  ports:
    # The port that this service should serve on.
    - port: 25565
      name: main
    - port: 25575
      name: rcon
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: minecraft
  type: LoadBalancer
